"""Add status

Revision ID: 6e0f991e4119
Revises: 8c72502d3178
Create Date: 2019-06-18 14:24:43.926464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0f991e4119'
down_revision = '8c72502d3178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'status')
    # ### end Alembic commands ###
